[colors]
background = '#f9f9ff'
foreground = '#191c20'

cursor_bg = '#3c6090'
cursor_fg = '#f9f9ff'
cursor_border = '#3c6090'

selection_bg = '#d4e3ff'
selection_fg = '#191c20'

ansi = ['#f9f9ff', '#8c0b0b', '#0b7209', '#7f7411', '#53a7ff', '#24497a', '#3c6090', '#1a1a1a']
brights = ['#2e2e2e', '#a52020', '#168c13', '#998c21', '#3d6dac', '#3fb3ff', '#6259ff', '#1a1a1a']
